language: ruby

os:
  - linux
  - osx

sudo: true

addons:
  firefox: latest
  chrome: stable

env:
  - TRAVIS_NODE_VERSION=6

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
      npm install
      npm install -g gulp
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osxy" ]]; then
      gulp build
      gulp test --coverage
      gulp docs
      gulp package
      gulp bower
      cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      gulp unittest
    fi
