language: ruby

os:
  - linux
  - osx

addons:
  firefox: latest
  chrome: stable

env:
  - TRAVIS_NODE_VERSION=6

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sh -e /etc/init.d/xvfb start; fi

install:
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install --dev
  - npm install -G gulp

script:
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      gulp build
      gulp test --coverage
      gulp docs
      gulp package
      gulp bower
      cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      gulp test
    fi
